Car price pred
deploifai/examples pull request #9
Opened 2023-07-26 09:52 UTC by nafis-ishrak

2023-07-27 03:07 UTC, 98sean98 requested changes
Require minor changes

2023-07-27 03:07 UTC, 98sean98 commented on CarPricePrediction/README.md
> +The python script requires a pickle file to be saved in the same directory: `model.pkl` and a `requirements.txt` file that includes the name and versions of all the packages used. The pickle files co
- not `model.pkl` but `RandomForestRegressor.pkl`
- minor grammar mistake in "The pickle file contains the Random Forest ..."

2023-07-27 03:07 UTC, 98sean98 commented on CarPricePrediction/README.md
> + -->
Is this section intended to be shown?

2023-07-27 03:28 UTC, 98sean98 commented
What's the currency of the `Present Price`? It's important to make this clear. And also the output is still using `lakhs`?

I think everything should either use `lakhs` or not use `lakhs` at all.

<img width="1028" alt="Screenshot 2023-07-27 at 11 24 57 AM" src="https://github.com/deploifai/examples/assets/22276614/7b632d0b-9d08-4a4d-925b-609643781063">

2023-07-28 07:34 UTC, nafis-ishrak commented
> 

docker image works perfectly. just didnt deploy the updated one on deploifai yet

2023-08-07 04:15 UTC, 98sean98 approved these changes

2023-08-07 04:15 UTC, merged